#!/bin/bash
Password="redhat"
User="admin"
OS_TOKEN=$(grep -Po "(?<=^admin_token = )[0-9a-f]{32}" /etc/keystone/keystone.conf)
OS_URL="http://127.0.0.1:35357/v2.0"
OS_IDENTITY_API_VERSION=2
OS_TOKEN=${OS_TOKEN} OS_URL=${OS_URL} OS_IDENTITY_API_VERSION=${OS_IDENTITY_API_VERSION} openstack user set --password ${Password} ${User}
